/**
 * Build script: TypeScript → Node.js SEA (Single Executable Application)
 *
 * Output: dist/equality-core.exe
 *
 * Steps:
 *  1. tsc  →  dist/index.js  (CJS bundle via esbuild for SEA compatibility)
 *  2. node --experimental-sea-config sea-config.json  →  equality-core.blob
 *  3. Copy node.exe → dist/equality-core.exe
 *  4. postject: inject blob into exe
 *  5. Copy better-sqlite3.node → dist/
 *  6. Remove blob
 */

import { execSync } from 'node:child_process'
import { copyFileSync, existsSync, rmSync, writeFileSync, readFileSync, mkdirSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '..')

function run(cmd, opts = {}) {
  console.log(`\n> ${cmd}`)
  execSync(cmd, { stdio: 'inherit', cwd: root, ...opts })
}

// 1. Bundle with esbuild JS API → CJS
//    方案：创建临时包裹入口 _sea_entry.cjs，内容为：
//      (async()=>{ await import('./src/index.ts') })()
//    esbuild 对这个入口做 bundle，顶层没有 await，可以正常输出 CJS
//    内部的 dynamic import 会被 esbuild inline 展开
console.log('\n> esbuild (JS API): src/index.ts → dist/index.js')
{
  let esbuild
  try {
    esbuild = await import('esbuild')
  } catch {
    run('npm install --save-dev esbuild')
    esbuild = await import('esbuild')
  }

  mkdirSync(resolve(root, 'dist'), { recursive: true })

  // 创建临时包裹入口：用 async IIFE + await import() 触发真实入口
  // esbuild 会把 dynamic import 静态分析并 inline bundle
  const wrapperEntry = resolve(root, 'dist', '_sea_entry.cjs')
  writeFileSync(wrapperEntry, `
// SEA CJS wrapper — generated by build-sea.mjs
const { createRequire } = require('module');
const _require = createRequire(import.meta.url || __filename);
(async () => {
  await Promise.resolve().then(() => require('./_sea_impl.js'));
})().catch(e => { console.error(e); process.exit(1); });
`.trim())

  // Step A: 先把 src/index.ts bundle 成 ESM（支持顶层 await）
  const implOut = resolve(root, 'dist', '_sea_impl.js')
  const r1 = await esbuild.build({
    entryPoints: [resolve(root, 'src', 'index.ts')],
    bundle: true,
    platform: 'node',
    target: 'node22',
    format: 'esm',
    outfile: implOut,
    external: [
      // better-sqlite3 的 JS 层打包进来，只把 .node 原生文件排除
      '@primno/dpapi',
      'chromium-bidi',
      'chromium-bidi/*',
      // playwright 本身不打包（体积太大且有循环依赖），但 playwright-core 打包进来
      'playwright',
    ],
    logLevel: 'warning',
  })
  if (r1.errors.length) process.exit(1)

  // Step B: 把 ESM bundle 用正则转成 CJS（bundle 后只剩 external import 语句）
  let impl = readFileSync(implOut, 'utf-8')

  // 辅助：把 ESM named imports "X as Y" 转成 CJS 解构 "X: Y"
  const namedToDestructure = (named) =>
    named.split(',').map(s => {
      const t = s.trim()
      const m = t.match(/^(\w+)\s+as\s+(\w+)$/)
      return m ? `${m[1]}: ${m[2]}` : t
    }).join(', ')

  impl = impl.replace(
    /^import\s+\*\s+as\s+(\w+)\s+from\s+['"]([^'"]+)['"]\s*;?/gm,
    (_, n, m) => `const ${n} = require('${m}');`
  )
  impl = impl.replace(
    /^import\s+(\w+)\s*,\s*\{\s*([^}]+)\}\s+from\s+['"]([^'"]+)['"]\s*;?/gm,
    (_, def, named, m) => `const ${def} = require('${m}');\nconst {${namedToDestructure(named)}} = ${def};`
  )
  impl = impl.replace(
    /^import\s+(\w+)\s+from\s+['"]([^'"]+)['"]\s*;?/gm,
    (_, n, m) => `const ${n} = require('${m}');`
  )
  impl = impl.replace(
    /^import\s*\{\s*([^}]+)\}\s+from\s+['"]([^'"]+)['"]\s*;?/gm,
    (_, named, m) => `const {${namedToDestructure(named)}} = require('${m}');`
  )
  impl = impl.replace(/import\.meta\.url/g, "require('url').pathToFileURL(__filename).href")
  impl = impl.replace(/import\.meta\.dirname/g, '__dirname')
  impl = impl.replace(/import\.meta\.filename/g, '__filename')
  impl = impl.replace(/^export\s+default\s+/gm, '')
  impl = impl.replace(/^export\s*\{[^}]*\}\s*;?\s*$/gm, '')
  // esbuild __require shim 没有 .resolve，替换成 __filename（bundle 后文件已内联，路径无意义）
  impl = impl.replace(/__require\d*\.resolve\s*\(/g, '((x) => __filename)(')
  // playwright-core 等库里的原生 require.resolve 在 SEA 里也不存在，同样降级
  impl = impl.replace(/\brequire\.resolve\s*\(/g, '((x) => __filename)(')
  writeFileSync(implOut, `'use strict';\n${impl.trim()}\n`)

  // Step C: 把包裹 IIFE + impl 合并成最终 index.js
  const wrapCode = `'use strict';\n(async () => {\n${impl.trim()}\n})().catch(e => { console.error(e); process.exit(1); });\n`
  writeFileSync(resolve(root, 'dist', 'index.js'), wrapCode)

  // 清理临时文件
  rmSync(wrapperEntry, { force: true })
  rmSync(implOut, { force: true })

  console.log('  ✅ esbuild 完成')
}

// 2. Generate SEA blob
run(`node --experimental-sea-config sea-config.json`)

// 3. Copy node.exe
const nodePath = process.execPath
const exeOut = resolve(root, 'dist', 'equality-core.exe')
console.log(`\n> Copying node.exe → ${exeOut}`)
copyFileSync(nodePath, exeOut)

// 4. Remove signature (required before injection on Windows)
try {
  run(`signtool remove /s "${exeOut}"`, { stdio: 'pipe' })
} catch {
  // signtool may not be available; continue
  console.log('  signtool not found – skipping signature removal (OK for dev)')
}

// 5. Inject blob via postject
const blob = resolve(root, 'equality-core.blob')
run(
  `npx postject "${exeOut}" NODE_SEA_BLOB "${blob}"` +
    ` --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2`,
)

// 6. 复制 better-sqlite3.node 到 dist/ 旁边（SEA 模式下从 exe 同级目录加载）
const sqliteNode = resolve(
  root,
  'node_modules',
  'better-sqlite3',
  'build',
  'Release',
  'better_sqlite3.node',
)
const sqliteOut = resolve(root, 'dist', 'better-sqlite3.node')
console.log(`\n> Copying better-sqlite3.node → ${sqliteOut}`)
copyFileSync(sqliteNode, sqliteOut)

// 7. 复制 @primno+dpapi.node 到 dist/ 旁边（Windows DPAPI 加密 API Key 用）
const arch = process.arch === 'arm64' ? 'win32-arm64' : 'win32-x64'
const dpapiNode = resolve(
  root,
  'node_modules',
  '@primno',
  'dpapi',
  'prebuilds',
  arch,
  '@primno+dpapi.node',
)
const dpapiOut = resolve(root, 'dist', '@primno+dpapi.node')
console.log(`\n> Copying @primno+dpapi.node → ${dpapiOut}`)
try {
  copyFileSync(dpapiNode, dpapiOut)
} catch (e) {
  console.warn('  ⚠ 复制 @primno+dpapi.node 失败（非 Windows 构建或包未安装），跳过:', e.message)
}

// 8. Cleanup
if (existsSync(blob)) rmSync(blob)

console.log(`\n✅  Built: ${exeOut}`)
console.log(`✅  Native module: ${sqliteOut}`)
console.log(`✔  将 dist/equality-core.exe、dist/better-sqlite3.node、dist/@primno+dpapi.node 一起分发`)
